//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module SoundMixer(
	//////////// Audio //////////
	input AUD_ADCDAT,
	inout AUD_ADCLRCK,
	inout AUD_BCLK,
	output AUD_DACDAT,
	inout AUD_DACLRCK,
	output AUD_XCK,

	//////////// CLOCK //////////
	input CLOCK2_50,
	input CLOCK3_50,
	input CLOCK4_50,
	input CLOCK_50,

	//////////// I2C for Audio and Video-In //////////
	output FPGA_I2C_SCLK,
	inout FPGA_I2C_SDAT,

	//////////// SEG7 //////////
	output[6:0] HEX0,
	output[6:0] HEX1,
	output[6:0] HEX2,
	output[6:0] HEX3,
	output[6:0] HEX4,
	output[6:0] HEX5,

	//////////// KEY //////////
	input[3:0] KEY,

	//////////// LED //////////
	output[9:0] LEDR,

	//////////// SW //////////
	input[9:0] SW
);

//=======================================================
//  REG/WIRE declarations
//=======================================================

//=======================================================
//  Structural coding
//=======================================================
	assign HEX5 = 7'b1111111;
	assign HEX4 = 7'b1111111;
	assign HEX3 = 7'b1111111;
	assign HEX2 = 7'b1111111;
	
	mixer mix (
		.audio_config_extern_SDAT (FPGA_I2C_SDAT),
		.audio_config_extern_SCLK (FPGA_I2C_SCLK),
		.audio_external_ADCDAT    (AUD_ADCDAT),
		.audio_external_ADCLRCK   (AUD_ADCLRCK),
		.audio_external_BCLK      (AUD_BCLK),
		.audio_external_DACDAT    (AUD_DACDAT),
		.audio_external_DACLRCK   (AUD_DACLRCK),
		.audio_pll_clk_clk        (AUD_XCK),
		.clk_clk                  (CLOCK_50),
		.hex_hex_signal_0         (HEX0),
		.hex_hex_signal_1         (HEX1),
		.key_key_signal           (KEY[1:0]),
		.reset_reset_n            (~SW[9])
	);
endmodule
